exclude: '^docs|/migrations/'
default_stages: [commit]

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: ['-l', '120', '--profile', 'black']
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black
        args: ['-l', '120', '-t', 'py310', '--skip-string-normalization']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: ['--python-version', '3.10', '--ignore-missing-imports', '-check-untyped-defs', '--show-error-codes']
        additional_dependencies: [tokenize-rt==3.2.0, types-mock, types-requests]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--ignore=E501,D102,D104,D107', --docstring-convecntion, google, --max-line-length, '120']
        additional_dependencies: [
          'flake8-blind-except',
          'flake8-docstrings',
          'flake8-bugbear',
          'flake8-comprehensions',
          'flake8-implicit-str-concat',
          'pydocstyle>=5.0.0',
        ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-toml
      - id: mixed-line-ending
